default:

minimal:
  selector : textarea.minimal
  menubar : false
  statusbar : false
  formats : {
    alignleft : {},
    aligncenter : {},
    alignright : {},
    alignfull : {},
    bold : {},
    italic : {},
    underline : {},
    strikethrough : {},
    forecolor : {},
    hilitecolor : {},
    custom_format : { styles : {color : red} }
  }
  
  toolbar:
    - image | link | media
  plugins:
    - image
    - link
    - media

revenue:
  selector: textarea.revenue
  menubar : true
  statusbar : false
  templates: [ 
    {title: 'Doce', description: 'Doce', content: '<br><br>My content'}
  ]
  toolbar:
    - template | styleselect | fontselect | bold italic | undo redo | searchreplace | image | link | preview | media | table | forecolor backcolor
  plugins:
    - visualblocks
    - searchreplace
    - preview
    - image
    - link
    - media
    - table
    - textcolor
    - template